### ISSUE TITLE
[BUG] Hostname as address is not working

### ISSUE THREAD

**Issue by aklo** [GravityWolfNotAmused/PlayerCountDiscordBot#48] opened 2022-09-12 19:37 UTC
I'm using docker compose to run the program. The docker was working fine a few days ago. The value for BOT_PUBADDRESSES is hostname.

**Screenshots**
![image](https://user-images.githubusercontent.com/3373492/189739994-72ae0993-3898-43ec-b927-ea71e0c26b62.png)

**Comment by GravityWolfNotAmused** [comment] 2022-09-12 19:38
Thank you for posting this, please give me one moment to look it over, and post somethings for myself.

**Comment by GravityWolfNotAmused** [comment] 2022-09-12 19:41
Can you please remove all tokens from your compose file and post it as well?

**Comment by aklo** [comment] 2022-09-13 02:50
BOT_NAMES: "ProjectZomboid"
       BOT_PUBADDRESSES: "hostname"
       BOT_PORTS: "16969"
       BOT_DISCORD_TOKENS: "*"
       BOT_UPDATE_TIME: "30"
       BOT_STATUSES: "0"
       BOT_USENAMETAGS: "false"
       BOT_PROVIDERTYPES: "0"
       BOT_APPLICATION_VARIABLES: "SteamAPIKey,*"

**Comment by GravityWolfNotAmused** [comment] 2022-09-13 04:21
@aklo I think I have determined the issue that you are facing, and have created a fix in #49 . The problem is that I was treating all API returns as if they were JSON object; however, address resolution is purely a string. This will be in dev shortly, if you could test the dev tag in docker <3

**Comment by aklo** [comment] 2022-09-13 07:12
Perfect! It's up and running now. Thank you so much!

**Comment by GravityWolfNotAmused** [comment] 2022-09-13 07:13
I'll release this to the latest tag tomorrow. Thank you for reporting your issue.

**Closed as completed** 2022-09-13 17:46 UTC
Labels: bug
